_extends: .github:.github/default-settings.yml

repository:
  name: react-ui-pairing-exercise

collaborators:
  - username: onb-githubuser
    permission: push

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true

repository:
  # See https://github.com/apps/settings for all available settings.
  name: react-ui-pairing-exercise
  description: null
  topics: "squad::Personal Savings, mission::Personal Savings, product::Transactional Bank, environment::Sandbox"
