# See https://developer.github.com/v3/repos/#edit for all available settings.

_extends: .github:.github/default-settings.yml

repository:
  name: react-ui-pairing-exercise

collaborators:
  - username: onb-githubuser
    permission: push

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
